/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

/**
 * Jupyter Interactive Widget View JSON schema.
 */
export interface IView {
  /**
   * Format version (major)
   */
  version_major?: number;
  /**
   * Format version (minor)
   */
  version_minor?: number;
  /**
   * Unique identifier of the widget model to be displayed
   */
  model_id?: string;
  required?: any;
}
